#!/bin/bash
# update the instance
yum update -y
 
# install jdk
yum install java-1.8.0-openjdk -y
yum install java-1.8.0-openjdk-devel -y
yum install git -y
 
update-alternatives --set java /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.25-0.b18.4.amzn1.x86_64/jre/bin/java
 
cd /home/ec2-user
 
# install Apache Maven
wget http://mirror.netcologne.de/apache.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz 
tar -xzvf apache-maven-3.3.9-bin.tar.gz
 
# get the code
git clone https://github.com/aschiffler/obd-kinesis.git

# create credentials file
mkdir .aws
cd .aws
echo "aws_access_key_id=" > credentials
echo "aws_secret_access_key=" > credentials
cd ../obd-kninesis  
 
# do the build
/home/ec2-user/apache-maven-3.3.9/bin/mvn package

# ToDo via SSH:
# input credentials in .aws/credentials 
# start application 'counter':
# /home/ec2-user/apache-maven-3.3.9/bin/mvn -Dwindow-with=30000 -Dupdate-rate=2000 -Pcounter exec:java